Week 1
OrlandoFabian/My_Portfolio pull request #1
Opened 2021-02-26 19:03 UTC by OrlandoFabian

Created the files for the different areas and populated my home page and work experience

2021-02-26 20:01 UTC, mcshen-sps requested changes
Nice work Orlando! I left a few minor comments. Keep it up!

2021-02-26 20:01 UTC, mcshen-sps commented on portfolio/src/main/webapp/index.html
> +              <li><a href="Contact.html">Contact</a></li>
Please be consistent with the style of your filenames. I recommend changing Projects -> projects, Contact -> contact. It also might be good to add some placeholder text in the empty files so a user knows that they're on the right page

2021-03-03 01:46 UTC, mcshen-sps reviewed
good work Orlando! It's become much neater!

I left a few new comments. click the "resolve conversation" button on comments that you've fixed, or you can also reply to comments if you have questions or if you have a reason not to make the change

2021-03-03 01:46 UTC, mcshen-sps commented on portfolio/src/main/webapp/homePage.css
> +    margin: 0;
keep your declarations in alphabetical order for consistency and ease of maintenance

2021-03-03 01:46 UTC, mcshen-sps commented on portfolio/src/main/webapp/index.html
> +              <div><img src="/images/me.png" /></div>
Whenever you have an image, it's good to include the `alt` attribute (e.g. `alt="portrait of Orlando"`). This will give screen readers a description of the image and also provide placeholder text in the case that the image can't be shown.

2021-03-03 01:46 UTC, mcshen-sps commented on portfolio/src/main/webapp/index.html
> +                    <button></button>
Is there a reason for this empty button?

2021-03-03 01:46 UTC, mcshen-sps commented on portfolio/src/main/webapp/script.js
>    const greeting = greetings[Math.floor(Math.random() * greetings.length)];
This comment still applies

2021-03-03 01:46 UTC, mcshen-sps commented on portfolio/src/main/webapp/index.html
> +
Try to be consistent with where you use whitespace. There's an extra newline here while there isn't one between the other `<p>` elements

2021-03-03 01:46 UTC, mcshen-sps commented on portfolio/src/main/webapp/index.html
> +      <section id="about me">
In general, try not to have spaces in ids. You could change this to kebab case (about-me) like you're using elsewhere

2021-03-03 01:46 UTC, mcshen-sps commented on portfolio/src/main/webapp/index.html
> +</html>
It's easier for git to keep track of diffs when there is an empty newline at the end of each file

2021-03-03 01:46 UTC, mcshen-sps commented on portfolio/src/main/webapp/homePage.css
> +body{
Add a space between the css selector and the opening `{`. In the rules below as well.
```suggestion
html {
    scroll-behavior: smooth
}

body {
```

2021-03-03 20:25 UTC, OrlandoFabian commented on portfolio/src/main/webapp/index.html
> +                    <button></button>
Yeah, that's the rectangle in the back that appears in the About Me photo. I can try using something else if it's necessary.

2021-03-03 20:27 UTC, OrlandoFabian commented on portfolio/src/main/webapp/index.html
> +</html>
Did not understood this. Can you be more clear about what you mean? Should I always add a newline at the end of the file whenever I commit?

2021-03-03 20:55 UTC, mcshen-sps commented on portfolio/src/main/webapp/index.html
> +                    <button></button>
It's a little confusing for other developers and for people using screen readers when elements aren't used for their intended purpose. Can you try using a `<div>` instead?

2021-03-03 20:55 UTC, mcshen-sps commented on portfolio/src/main/webapp/index.html
> +</html>
In general the last line in a file should be empty. You don't have to add another whenever you commit. It isn't strictly necessary, but there are tools that will behave slightly differently if it isn't there, so GitHub shows a warning

2021-03-03 20:55 UTC, mcshen-sps commented on portfolio/src/main/webapp/index.html
> +                    <li>Contact me</li>
I suggest removing these list items until the section they should link to is ready. It's a little confusing when they look the same as the links but they don't do anything.

2021-03-03 23:56 UTC, mcshen-sps approved these changes
Looks good! Great work!

2021-03-03 23:57 UTC, merged